### ISSUE TITLE
Not on Hackage

### ISSUE THREAD

**Issue by ryantm** [crufter/haquery#1]
This is not a package. Perhaps making it a package would improve reuse?

**Comment by crufter** [comment]
Hey!

Sorry for the late reply.
Do you mean it's not on Hackage? Or the fact it is at the top level instead of eg. Web.Haquery?

Send a PR if so and I merge it.

**Comment by ryantm** [comment]
Hi.

Sorry for not being clear. I meant that it is not on Hackage.

Ryan

**Comment by domenkozar** [comment]
@crufter do you plan to publish hquery on hackage.haskell.org? Otherwise I'll fork and publish, but I'd really like to avoid that :)

**Comment by crufter** [comment]
Hey @domenkozar, yeah, I will look into it in the next couple of days.

**Comment by domenkozar** [comment]
@crufter do you need some help with that? I'd start using the package immediately, so I'll likely test it as soon as it's there.

**Comment by domenkozar** [comment]
Two things that need to be done at least:
- remove version restrictions in .cabal file
- rename `src/haquery` to `src/Haquery`

**Comment by domenkozar** [comment]
Opened a PR for that: https://github.com/crufter/haquery/pull/3

**Comment by crufter** [comment]
@domenkozar merged! I had a hectic week, the weekend should be a bit more chilled so I will have a look as the first thing in Saturday morning. Sorry for the delay and thanks for the PR.

**Comment by crufter** [comment]
@domenkozar What is a good category for this package on Hackage you reckon?

**Comment by domenkozar** [comment]
I'd say HTML.

**Comment by crufter** [comment]
@domenkozar Sounds good to me.

**Comment by crufter** [comment]
`The dependency 'build-depends: base' does not specify an upper bound on the version number. Each major release of the 'base' package changes the API in various ways and most packages will need some changes to compile with it. The recommended practise is to specify an upper bound on the version of the 'base' package. This ensures your package will continue to build when a new major version of the 'base' package is released. If you are not sure what upper bound to use then use the next major version. For example if you have tested your package with 'base' version 4.5 and 4.6 then use 'build-depends: base >= 4.5 && < 4.7'.`

**Comment by crufter** [comment]
Ok this is probably not the prettiest release but here we are:

`There were some warnings:

No 'description' field.
Exposed modules use unallocated top-level names: Haquery`

https://hackage.haskell.org/package/haquery-0.1.1.2

@domenkozar Can you try if it's all good?

**Comment by domenkozar** [comment]
```
In the dependencies for haquery-0.1.1.2:
    base-4.8.2.0 must match >=4.5 && <4.7 (latest applicable is 4.6.0.1)
```

Is there a reason not to support base-4.8? It did compile for me when haquery was used from git against base-4.8.2.0.

**Comment by domenkozar** [comment]
@crufter I've even tested it on base-4.9, which is part of stackage TLS 7.3 on GHC 8.0.1 and it works.

Therefore I propose:

`base >= 4.5 && < 4.10`

**Comment by crufter** [comment]
@domenkozar makes sense

made an other release: https://hackage.haskell.org/package/haquery-0.1.1.3

**Comment by domenkozar** [comment]
Awesome :) Works with GHC 8.0.1, thank you! This can be closed now.

**Comment by crufter** [comment]
Nice!
