### ISSUE TITLE
Upload haddoc API docs to hackage

### ISSUE THREAD

**Issue by domenkozar** [crufter/haquery#9]
Currently there are no docs on hackage, it would be useful to generate them.

See https://hackage.haskell.org/package/haquery

cc @crufter

**Comment by crufter** [comment]
Will make sure the next release contains one. Bit out of the loop with Haskell things, gonna fix that. Thanks

**Comment by domenkozar** [comment]
@crufter I think you should be able to rebuild it at https://hackage.haskell.org/package/haquery-0.1.1.3/reports/

**Comment by domenkozar** [comment]
Done by @glguy using https://github.com/ekmett/lens/blob/master/scripts/hackage-docs.sh
